######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&dSelect a Class &9[Temp Menu]'

  # rows - the number of rows of the chest - REQUIRED
  rows: 6

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: 'lol_ClassSelector'

  # auto-refresh - OPTIONAL
  # How frequently the menu will be refreshed, in seconds.
  # Useful if you have variables in items' descriptions.
  auto-refresh: 5

  # This command command will be execute when the menu is opened.
  # Supports all the icon command types.
  open-action: ''

  # open-with-item - OPTIONAL
  # The menu will open only right-clicking with orange wool [35:1]
  open-with-item:
    id: wool:1
    left-click: false
    right-click: false


######################
#+                  +#
#       ITEMS        #
#+                  +#
######################

swordsman:
  COMMAND: 'op: class profess Swordsman; op: ie give OakWoodSword {player} 1'
  NAME: '&2Become a Swordsman'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&a8/10 &7Defense'
    - '&e6/10 &7Healing'
    - '&e6/10 &7Support'
    - '&e6/10 &7Anti-Support'
    - '&e6/10 &7Reach'
    - '&a7/10 &7Ground Mobility'
    - '&e5/10 &7Air Mobility'
    - '&a7/10 &7Elemental Variety'
    - ''
    - '&6Offensive Tank'
    - '&f'
    - '&f● Mainly short ranged, but has decent projectiles.'
    - '&f● Has a good combo game.'
    - '&f● Best described as "simple, yet effective."'
    - '&f● Built better for Beginners, but without holding'
    - '&f   back those who want to go pro with this.'
    - '&f● Arguably the most customizable class.'
    - '&f● '
  ID: 1
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 1

mage:
  COMMAND: 'op: class profess Mage; op: ie give OakWoodWand {player} 1'
  NAME: '&2Become a Mage'
  LORE:
    - ''
    - '&a8/10 &7Damage'
    - '&c3/10 &7Defense'
    - '&a7/10 &7Healing'
    - '&a8/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&a8/10 &7Reach'
    - '&e4/10 &7Ground Mobility'
    - '&e4/10 &7Air Mobility'
    - '&a7/10 &7Elemental Variety'
    - ''
    - '&6Offensive/Support.'
    - '&f'
    - '&f● Mainly long ranged, but has melee AOE skills.'
    - '&f● Has multible attacks for most elements rather'
    - '&f   than at least 1 unique elemental attack.'
    - '&f● Has a skill to cure all negative potion effects.'
    - '&f● Has the fastest mana regeneration.'
    - '&f● '
    - '&f● '
  ID: 2
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 1

archer:
  COMMAND: 'op: class profess Archer; op: ie give OakWoodBow {player} 1'
  NAME: '&2Become an Archer'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&c3/10 &7Defense'
    - '&e5/10 &7Healing'
    - '&e5/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&a8/10 &7Reach'
    - '&a8/10 &7Ground Mobility'
    - '&a7/10 &7Air Mobility'
    - '&a8/10 &7Elemental Variety'
    - ''
    - '&6Offensive/Flanking.'
    - '&f'
    - '&f● Almost entirely long ranged.'
    - '&f● Unsafe to use at close range.'
    - '&f● The very high amount of mobility allows for'
    - '&f   the user to flank and escape effectively.'
    - '&f● Has extremely effective spacing tools.'
    - '&f● '
    - '&f● '
  ID: 3
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 1

thief:
  COMMAND: 'op: class profess Thief; op: ie give OakWoodDagger {player} 1'
  NAME: '&2Become a Thief'
  LORE:
    - ''
    - '&a8/10 &7Damage'
    - '&e5/10 &7Defense'
    - '&c4/10 &7Healing'
    - '&a7/10 &7Support'
    - '&a7/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&a7/10 &7Ground Mobility'
    - '&a7/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - ''
    - '&6Offensive.'
    - '&f'
    - '&f● Best close ranged. Weak at long ranged.'
    - '&f● Its only projectile is also one of the'
    - '&f   best projectiles on the server.'
    - '&f● Has incredible combo potential.'
    - '&f● Has a pseudo "stealth damage" bonus effect.'
    - '&f'
    - '&f'
  ID: 4
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 2

beast:
  COMMAND: 'op: class profess Beast; op: ie give OakWoodClaw {player} 1'
  NAME: '&2Become a Beast'
  LORE:
    - ''
    - '&b10/10 &7Damage'
    - '&e4/10 &7Defense'
    - '&e5/10 &7Healing'
    - '&e5/10 &7Support'
    - '&e6/10 &7Anti-Support'
    - '&e5/10 &7Reach'
    - '&b10/10 &7Ground Mobility'
    - '&e5/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - ''
    - '&6Rush Down/Hit and Run.'
    - '&f'
    - '&f● Best melee game on the server.'
    - '&f● Has a weak, short ranged projectile.'
    - '&f● Can easilly rush towards any grounded enemy.'
    - '&f● Suffers from targeting mid-air targets.'
    - '&f● Has the best stamina regeneration in combat.'
    - '&f'
    - '&f'
  ID: 5
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 2

automation:
  COMMAND: 'op: class profess Automation; op: ie give OakWoodCannon {player} 1'
  NAME: '&2Become a Automation'
  LORE:
    - ''
    - '&a8/10 &7Damage'
    - '&a9/10 &7Defense'
    - '&e4/10 &7Healing'
    - '&a7/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&e5/10 &7Ground Mobility'
    - '&e4/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - '&f'
    - '&6Defensive/Heavy Spacing'
    - '&f'
    - '&f● Has the strongest spacing skills.'
    - '&f● Has skills that create litteral walls'
    - '&f   and fences using skills.'
    - '&f● Spacing skills are mainly damaging skills.'
    - '&f● Theme: "Best offensive is a good defense."'
    - '&f'
    - '&f'
  ID: 6
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 2

deity:
  COMMAND: 'op: class profess Deity; op: ie give OakWoodGlaive {player} 1'
  NAME: '&2Become a Deity'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&c2/10 &7Defense'
    - '&e6/10 &7Healing'
    - '&e4/10 &7Support'
    - '&a8/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&e5/10 &7Ground Mobility'
    - '&a9/10 &7Air Mobility'
    - '&a7/10 &7Elemental Variety'
    - '&f'
    - '&6Glass Cannon/Spacing'
    - '&f'
    - '&f● Good damage at all ranges.'
    - '&f● Can easilly mix up melee and ranged'
    - '&f   skills, which is useful for switching'
    - '&f    between DPS and spacing in combat.'
    - '&f● Later gets a flight type skill.'
    - '&f'
    - '&f'
  ID: 12
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 3

reaper:
  COMMAND: 'op: class profess Reaper; op: ie give OakWoodScythe {player} 1'
  NAME: '&2Become a Reaper'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&e4/10 &7Defense'
    - '&e6/10 &7Healing'
    - '&e5/10 &7Support'
    - '&b10/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&a8/10 &7Ground Mobility'
    - '&c2/10 &7Air Mobility'
    - '&e4/10 &7Elemental Variety'
    - '&f'
    - '&6Debuff/Resource Stealer'
    - '&f'
    - '&f● Has the best lifesteal.'
    - '&f● Has the best mana steal.'
    - '&f● Immunity to the damage effects of Wither.'
    - '&f● Kills heal HP and Mana.'
    - '&f● Later can place a "Death Field" trap.'
    - '&f● Is able to block certain buffs later on.'
    - '&f'
  ID: 13
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 3

gunman:
  COMMAND: 'op: class profess Gunman; op: ie give BasicPistol {player} 1'
  NAME: '&2Become a Gunman'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&a8/10 &7Defense'
    - '&e4/10 &7Healing'
    - '&e4/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&b10/10 &7Reach'
    - '&a7/10 &7Ground Mobility'
    - '&e6/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - '&f'
    - '&6Offensive/Flanking'
    - '&f'
    - '&f● Primarilly ranged.'
    - '&f● Has a variety of grenades.'
    - '&f● Able to use Pistol, Shotgun and'
    - '&f   Burst Fire with their right click.'
    - '&f● Later gets a long ranged Grappling Hook.'
    - '&f'
    - '&f'
  ID: 14
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 3

Synergist:
  COMMAND: 'op: class profess Synergist; op: ie give WoodenChakram {player} 1'
  NAME: '&2Become a Synergist'
  LORE:
    - ''
    - '&e6/10 &7Damage'
    - '&e4/10 &7Defense'
    - '&b10/10 &7Healing'
    - '&b10/10 &7Support'
    - '&a8/10 &7Anti-Support'
    - '&e6/10 &7Reach'
    - '&c3/10 &7Ground Mobility'
    - '&a6/10 &7Air Mobility'
    - '&a8/10 &7Elemental Variety'
    - '&f'
    - '&6Healing/Support'
    - '&f'
    - '&f● Primarilly Close ranged.'
    - '&f● Is able to use a shield that heals'
    - '&f   mana when taking damage.'
    - '&f● Later able to place a healing field.'
    - '&f● Has a projectile that heals friendly units.'
    - '&f'
    - '&f'
  ID: 15
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 4

Bard:
  COMMAND: 'op: class profess Bard; op: minecraft:give @p minecraft:diamond_pickaxe 1 1 {display:{Name:"§fOak Wood Harp",Lore:["§7Class Req - Bard","§7Level Req - 1","§7Atack Speed - Normal","§7Melee Damage - 5","§7Skill Damage - 5"]},HideFlags:63,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:546076,UUIDMost:598652,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-1,Operation:0,UUIDLeast:126919,UUIDMost:523053,Slot:"mainhand"}]}'
  NAME: '&2Become a Bard &6--[&bBeta&6]--'
  LORE:
    - ''
    - '&e5/10 &7Damage'
    - '&e5/10 &7Defense'
    - '&a8/10 &7Healing'
    - '&a9/10 &7Support'
    - '&a7/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&c3/10 &7Ground Mobility'
    - '&e5/10 &7Air Mobility'
    - '&e4/10 &7Elemental Variety'
    - ''
    - '&6Battle Healer'
    - '&f'
    - '&f● Has great AOE range, and best minimal range.'
    - '&f● Great at dealing decent damage and healing.'
    - '&f● Mainly cooldown relient.'
    - '&f● Can eventually buff nearly everything.'
    - '&f● &6--[&bIn Beta&6]--'
    - '&f'
    - '&f'

  ID: 16
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 4

DragonKnight:
  COMMAND: 'op: class profess Dragon-Knight; op: ie give WoodenSpear {player} 1'
  NAME: '&2Become a Dragon-Knight'
  LORE:
    - ''
    - '&a8/10 &7Damage'
    - '&c3/10 &7Defense'
    - '&e5/10 &7Healing'
    - '&e5/10 &7Support'
    - '&a7/10 &7Anti-Support'
    - '&a8/10 &7Reach'
    - '&a8/10 &7Ground Mobility'
    - '&a9/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - '&f'
    - '&6Rush Down/Flanking'
    - '&f'
    - '&f● Fights at all ranges.'
    - '&f● Has a Thorns like passive.'
    - '&f● Right Click skill is the longest'
    - '&f   ranged attack on the server.'
    - '&f● Takes less damage when in mid-air.'
    - '&f'
    - '&f'
  ID: 17
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 4

Insect:
  COMMAND: 'op: class profess Insect; op: ie give WoodenPincer {player} 1'
  NAME: '&2Become an Insect'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&a8/10 &7Defense'
    - '&e4/10 &7Healing'
    - '&e4/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&a6/10 &7Reach'
    - '&a8/10 &7Ground Mobility'
    - '&a8/10 &7Air Mobility'
    - '&e4/10 &7Elemental Variety'
    - '&f'
    - '&6Rush Down/Flanking'
    - '&f'
    - '&f● Fights at close to mid range.'
    - '&f● Can pretty much fly.'
    - '&f● Has the most poisoning skills.'
    - '&f● Deals bonus damage to poisoned enemies.'
    - '&f● Has a "flight mode" as a right click skill.'
    - '&f'
    - '&f'
  ID: 18
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 5

Archangel:
  COMMAND: 'op: class profess Archangel; op: ie give WoodenHammer {player} 1'
  NAME: '&2Become a Archangel'
  LORE:
    - ''
    - '&e6/10 &7Damage'
    - '&a9/10 &7Defense'
    - '&a8/10 &7Healing'
    - '&e6/10 &7Support'
    - '&e5/10 &7Anti-Support'
    - '&c3/10 &7Reach'
    - '&c3/10 &7Ground Mobility'
    - '&e5/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - '&f'
    - '&6Tank/Healer'
    - '&f'
    - '&f● Fights close range.'
    - '&f● Able to place a defensive field.'
    - '&f● Uses hack and slash like combos.'
    - '&f● Has one of the best defense out of all classes.'
    - '&f● Has a projectile that goes through enemies.'
    - '&f'
    - '&f'
  ID: 19
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 5

Archdemon:
  COMMAND: 'op: class profess Archdemon; op: ie give WoodenCrossbow {player} 1'
  NAME: '&2Become a Archdemon'
  LORE:
    - ''
    - '&a9/10 &7Damage'
    - '&e5/10 &7Defense'
    - '&e5/10 &7Healing'
    - '&c3/10 &7Support'
    - '&a7/10 &7Anti-Support'
    - '&a7/10 &7Reach'
    - '&a7/10 &7Ground Mobility'
    - '&b10/10 &7Air Mobility'
    - '&e6/10 &7Elemental Variety'
    - '&f'
    - '&6Damage/Flanking'
    - '&f'
    - '&f● Fights at most ranges.'
    - '&f● Likes to go for style points.'
    - '&f● Combo focused class.'
    - '&f● Able to stay in the air for a while.'
    - '&f● Has a skill that grants extended invincibility.'
    - '&f'
    - '&f'
  ID: 20
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 5

Phoenix:
  COMMAND: 'op: class profess Phoenix; op: give {player} minecraft:wooden_sword 1 1 {display:{Name:"§fOak Wood Khopesh",Lore:["§7Class Req - Phoenix","§7Level Req - 1","§7Atack Speed - Normal","§7Melee Damage - 5","§7Skill Damage - 5"]},HideFlags:63,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:546076,UUIDMost:598652,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-1,Operation:0,UUIDLeast:126919,UUIDMost:523053,Slot:"mainhand"}]}'
  NAME: '&2Become a Phoenix'
  LORE:
    - ''
    - '&b10/10 &7Damage'
    - '&a8/10 &7Defense'
    - '&e6/10 &7Healing'
    - '&e5/10 &7Support'
    - '&c2/10 &7Anti-Support'
    - '&e5/10 &7Reach'
    - '&a7/10 &7Ground Mobility'
    - '&b10/10 &7Air Mobility'
    - '&e5/10 &7Elemental Variety'
    - '&f'
    - '&6Defense/Flanking'
    - '&f'
    - '&f● Mainly short ranged, they only have 1 projectile.'
    - '&f● Has a strong combo game.'
    - '&f● Mainly kills using various trap type skills.'
    - '&f● Has by far the best air mobility.'
    - '&f● Takes little damage from the Ignition status effect.'
    - '&f● Gains stamina slightly faster.'
    - '&f● Very hard class to master.'
  ID: 21
  KEEP-OPEN: false
  POSITION-X: 1
  POSITION-Y: 6
SeaTurtle:
  COMMAND: 'op: class profess Sea-Turtle; op: give {player} minecraft:wooden_sword 1 1 {display:{Name:"§fOak Wood Khopesh",Lore:["§7Class Req - Sea-Turtle","§7Level Req - 1","§7Atack Speed - Normal","§7Melee Damage - 8","§7Skill Damage - 8"]},HideFlags:63,Unbreakable:1b,AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5,Operation:0,UUIDLeast:546076,UUIDMost:598652,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-1,Operation:0,UUIDLeast:126919,UUIDMost:523053,Slot:"mainhand"}]}'
  NAME: '&2Become a Sea-turtle'
  LORE:
    - ''
    - '&a7/10 &7Damage'
    - '&b10/10 &7Defense'
    - '&a7/10 &7Healing'
    - '&a7/10 &7Support'
    - '&c2/10 &7Anti-Support'
    - '&e5/10 &7Reach'
    - '&e5/10 &7Ground Mobility'
    - '&e5/10 &7Air Mobility'
    - '&e6/10 &7Elemental Variety'
    - '&f'
    - '&6Healing Support Tank'
    - '&f'
    - '&f● '
    - '&f● '
    - '&f● '
    - '&f● Do not use this class yet,'
    - '&f● It is not finished yet'
    - '&f● '
    - '&f● '
  ID: 22
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 6