######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&5Automation Class Info'

  # rows - the number of rows of the chest - REQUIRED
  rows: 6

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: 'TS_automation'

  # auto-refresh - OPTIONAL
  # How frequently the menu will be refreshed, in seconds.
  # Useful if you have variables in items' descriptions.
  auto-refresh: 5

  # This command command will be execute when the menu is opened.
  # Supports all the icon command types.
  open-action: ''

  # open-with-item - OPTIONAL
  # The menu will open only right-clicking with orange wool [35:1]
  open-with-item:
    id: wool:1
    left-click: false
    right-click: false


######################
#+                  +#
#       ITEMS        #
#+                  +#
######################


automation:
  NAME: '&6Automation'
  LORE:
    - '&fClass Infomation'
    - ''
    - '&f-Color Guide-'
    - ''
    - '&8Really Bad'
    - '&fBad'
    - '&2Ok'
    - '&5Good'
    - '&6Great'
    - '&bExcellent'
    - ''
  ID: '273:1'
  POSITION-X: 5
  POSITION-Y: 1
  KEEP-OPEN: true
damage:
  NAME: '&fDamage Output'
  LORE:
    - ''
    - '&eMelee Damage: &f3/10'
    - '&eSkill Damage: &68/10'
    - ''
    - '&7Automation lacks in any close'
    - '&7ranged damage, but has great'
    - '&7long ranged skill damage skills'
    - ''
  ID: Iron_sword
  POSITION-X: 3
  POSITION-Y: 3
  KEEP-OPEN: true

defense:
  NAME: '&fDefenses'
  LORE:
    - ''
    - '&eMelee Defense: &56/10'
    - '&eSkill Defense: &57/10'
    - ''
    - '&7Automation has a base'
    - '&7resistance to a few elements.'
    - '&7Automation has a skill that'
    - '&7increases all damage resistance'
    - '&7globally for a short time.'
    - '&7A combination of these things'
    - '&7make Automation somewhat'
    - '&7durable, yet situational.'
    - ''
  ID: Iron_chestplate
  POSITION-X: 4
  POSITION-Y: 3
  KEEP-OPEN: true

elementalvariety:
  NAME: '&fElemental Variety'
  LORE:
    - ''
    - '&eElement Count: &f3/10'
    - ''
    - '&7As a base class, it uses mainly'
    - '&7Fire and Thunder.'
    - '&7Also of course Neutral.'
    - ''
  ID: blaze_powder
  POSITION-X: 5
  POSITION-Y: 3
  KEEP-OPEN: true

support:
  NAME: '&fSupport'
  LORE:
    - ''
    - '&eSelf-Support: &56/10'
    - '&eAlly-Support: &81/10'
    - '&eEnemy Anti-Support: &24/10'
    - ''
    - '&7As a class focused on damage'
    - '&7and range, it needs support'
    - '&7elementally, as it lacks elemental'
    - '&7variety throughout its whole'
    - '&7class tree.'
    - '&7Automation is able to'
    - '&7Slow and Burn its targets.'
    - '&7This class has skills that'
    - '&7increase defense, heal, and'
    - '&7grant Regeneration to itself.'
    - '&7'
  ID: brewing_stand
  POSITION-X: 6
  POSITION-Y: 3
  KEEP-OPEN: true

healing:
  NAME: '&fHealing'
  LORE:
    - ''
    - '&eSelf-Healing: &24/10'
    - '&eAlly-Healing: &81/10'
    - ''
    - '&7Automation as a base class can'
    - '&7only heal through its "Nano-Repair"'
    - '&7skill. Grants a small amount of'
    - '&7healing, and Regeneration.'
    - '&7However, the regeneration from this'
    - '&7skill is canceled when the player'
    - '&7takes damage, so be careful.'
    - '&7'
  ID: potion
  POSITION-X: 7
  POSITION-Y: 3
  KEEP-OPEN: true

hoarding:
  NAME: '&fHoard Capabilities'
  LORE:
    - ''
    - '&eHoard Handling: &56/10'
    - ''
    - '&7This means how well a class'
    - '&7does against a hoard of mobs'
    - '&7based on its damage and defenses.'
    - '&7Automation has good skills for'
    - '&7hoard handling, but each cost a lot of'
    - '&7resources. "Shoot"''s beam,'
    - '&7"Missile", and "Missile"''s Napalm'
    - '&7each deal alot of AOE damage.'
    - '&7"Missile" is the most reliable, as'
    - '&7it uses up only a small amount of'
    - '&7tech, which Automation gains easilly'
    - '&7through hitting multible targets using'
    - '&7the "Shoot" skill.'
    - '&7'
  ID: skull:2
  POSITION-X: 3
  POSITION-Y: 4
  KEEP-OPEN: true


bossing:
  NAME: '&fBoss Battle Capabilities'
  LORE:
    - ''
    - '&eBoss Handling: &57/10'
    - ''
    - '&7This means how well a class'
    - '&7does in boss battles.'
    - '&7Even though bosses vary,'
    - '&7Automation''s range and good damage'
    - '&7is key. "Shoot" easilly gains tech'
    - '&7in both 1v1s and Hoard based fights.'
    - '&7Automation is able to heal themself'
    - '&7as well as raise defenses. Good for'
    - '&7longer fights. Main issue is'
    - '&7Automation''s lack of elemental'
    - '&7damage variety.'
    - '&7'
  ID: skull:1
  POSITION-X: 4
  POSITION-Y: 4
  KEEP-OPEN: true




range:
  NAME: '&fAttack Range'
  LORE:
    - ''
    - '&eReach: &b10/10'
    - ''
    - '&7Automation''s range is one of the best,'
    - '&7tied to Gunman. Reliable and accurate'
    - '&7skills with hitboxes a abit wider than'
    - '&7they seem. A skilled Automation could'
    - '&7easilly launch a "Missile" across the'
    - '&7arena from anywhere. The more advanced'
    - '&7classes do alot of with this range later'
    - '&7on, having some very frightening skills'
    - '&7with some frightening amounts of damage.'
    - '&7'
  ID: bow
  POSITION-X: 6
  POSITION-Y: 4
  KEEP-OPEN: true



movement:
  NAME: '&fClass Mobility'
  LORE:
    - ''
    - '&eMovement: &f3/10'
    - ''
    - '&7Automation doesn''t have any base Agility.'
    - '&7Automation''s "Thruster" allows for'
    - '&7full fall damage immunity, and keeps'
    - '&7the caster in place.'
    - '&7More advanced classes have upgraded'
    - '&7thrusters that allow different functions.'
    - '&7'
  ID: feather
  POSITION-X: 7
  POSITION-Y: 4
  KEEP-OPEN: true



basestats:
  NAME: '&fBase Class Stats Info'
  LORE:
    - ''
    - '&eHealth: &642 (+2 every level)'
    - '&eMana: &636 (+2 every level)'
    - '&eStrength: &f1 (+1 every level)'
    - '&eIntelligence: &f1 (+1 every level)'
    - '&eEndurance: &f5'
    - '&eWillpower: &210'
    - '&eFireDMG: &210%'
    - '&eThunderDMG: &210%'
    - '&eFireDEF: &210%'
    - '&eLightDEF: &210%'
    - '&eEarthDEF: &210%'
    - '&eWindDEF: &210%'
    - ''
  ID: nether_star
  POSITION-X: 5
  POSITION-Y: 4
  KEEP-OPEN: true


ProfessClass:
  COMMAND: 'op: playsound pda.logon ambient {player} ~ ~ ~ 1 1; op: class profess Automation; console: give {player} 273 1 1 {HideFlags:6,AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:5.8,Operation:0,UUIDLeast:221175,UUIDMost:741575,Slot:"mainhand"},{AttributeName:"generic.attackSpeed",Name:"generic.attackSpeed",Amount:-3,Operation:0,UUIDLeast:222945,UUIDMost:534625,Slot:"mainhand"}],Unbreakable:1,display:{Name:"§fOak Arm Cannon",Lore:["§7Class Req - Automation","§7Level Req - 1","§7Attack Speed - Very Slow","§7Melee Damage - 4.8","§7Skill Damage - 5.8"]}}'
  NAME: '&fProfess to a Automation'
  LORE:
    - '&7Click here to successfully profess'
    - '&7to a &6Automation!'
    - ''
    - '&7You can change class accounts later'
    - '&7if you change your mind.'
  ID: wool:5
  KEEP-OPEN: true
  POSITION-X: 3
  POSITION-Y: 6



UNProfessClass:
  COMMAND: 'op: playsound pda.recycle ambient {player} ~ ~ ~ 1 1; op: class reset confirm'
  NAME: '&fUnprofess current class'
  LORE:
    - '&7Click here to unprofess your'
    - '&7currently selected class.'
    - ''
    - '&7You can change class accounts later'
    - '&7if you change your mind.'
  ID: wool:4
  KEEP-OPEN: true
  POSITION-X: 5
  POSITION-Y: 6


exitmenu:
  COMMAND: 'op: playsound pda.hardware_remove ambient {player} ~ ~ ~ 1 1'
  NAME: '&fExit Menu'
  LORE:
    - '&7Exits this GUI'
    - ''
    - '&7ps. ESC and your inventory button'
    - '&7also quick exits the menus'
  ID: wool:14
  POSITION-X: 7
  POSITION-Y: 6
