######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&5Select a Class to Profess'

  # rows - the number of rows of the chest - REQUIRED
  rows: 3

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: 'cl'

  # auto-refresh - OPTIONAL
  # How frequently the menu will be refreshed, in seconds.
  # Useful if you have variables in items' descriptions.
  auto-refresh: 5

  # This command command will be execute when the menu is opened.
  # Supports all the icon command types.
  open-action: ''

  # open-with-item - OPTIONAL
  # The menu will open only right-clicking with orange wool [35:1]
  open-with-item:
    id: wool:1
    left-click: false
    right-click: false


######################
#+                  +#
#       ITEMS        #
#+                  +#
######################


swordsman:
  COMMAND: 'op: cl1'
  NAME: '&6Swordsman &fClass menu'
  LORE:
    - '&7Opens the Swordsman class selection menu'
    - ''
  ID: 268
  POSITION-X: 1
  POSITION-Y: 2
  KEEP-OPEN: true
mage:
  COMMAND: 'op: cl2'
  NAME: '&6Mage &fClass menu'
  LORE:
    - '&7Opens the Mage class selection menu'
    - ''
  ID: 280
  POSITION-X: 2
  POSITION-Y: 2
  KEEP-OPEN: true
archer:
  COMMAND: 'op: cl3'
  NAME: '&6Archer &fClass menu'
  LORE:
    - '&7Opens the Archer class selection menu'
    - ''
  ID: 261
  POSITION-X: 3
  POSITION-Y: 2
  KEEP-OPEN: true
assassin:
  COMMAND: 'op: cl4'
  NAME: '&6Assassin &fClass menu'
  LORE:
    - '&7Opens the Assassin class selection menu'
    - ''
  ID: 359
  POSITION-X: 4
  POSITION-Y: 2
  KEEP-OPEN: true
beast:
  COMMAND: 'op: cl5'
  NAME: '&6Beast &fClass menu'
  LORE:
    - '&7Opens the Beast class selection menu'
    - ''
  ID: 270
  DATA-VALUE: 1
  POSITION-X: 5
  POSITION-Y: 2
  KEEP-OPEN: true
automation:
  COMMAND: 'op: cl6'
  NAME: '&6Automation &fClass menu'
  LORE:
    - '&7Opens the automation class selection menu'
    - ''
  ID: 273
  DATA-VALUE: 1
  POSITION-X: 6
  POSITION-Y: 2
  KEEP-OPEN: true
deity:
  COMMAND: 'op: cl7'
  NAME: '&6Deity &fClass menu'
  LORE:
    - '&7Opens the Deity class selection menu'
    - ''
  ID: 274
  DATA-VALUE: 1
  POSITION-X: 7
  POSITION-Y: 2
  KEEP-OPEN: true
gunman:
  COMMAND: 'op: cl8'
  NAME: '&6Gunman &dComing Soon &fClass menu'
  LORE:
    - '&7Opens the Gunman Class menu'
    - ''
  ID: 293
  DATA-VALUE: 2
  POSITION-X: 8
  POSITION-Y: 2
  KEEP-OPEN: true
stalker:
  COMMAND: 'op: cl9'
  NAME: '&6Stalker &dComing Soon &fClass menu'
  LORE:
    - '&7Opens the Stalker class selection menu'
    - ''
  ID: 2266
  DATA-VALUE: 0
  POSITION-X: 9
  POSITION-Y: 2
  KEEP-OPEN: true