version: 4.0.7
options:
## Should the plugin be in debug mode?
## If you want help with the plugin in the Discord channel,
## please turn this setting on.
  debug: false
  hooking:
## Should the plugin hook into mcMMO and cancel
## mcMMO's repair event? This is available
## as mcMMO will allow players to rename items
## via repairing.
    mcmmo: false
## Should monsters be given random names? Pulls from the
## resources/mobnames folder. general.txt applies to all
## monsters, while a creeper.txt will only apply to
## creepers.
  give-mobs-names: false
## Should all mobs be given random names? This includes
## animals like cows and sheep. Pulls from the
## resources/mobnames folder. general.txt applies to all
## monsters, while a creeper.txt will only apply to
## creepers.
  give-all-mobs-names: false
## Should mobs be given the equipment when they spawn or
## should the items only be dropped on death? This defaults
## to true so that players can identify mobs that will drop
## sweet loot.
  display-mob-equipment: true
## Should mobs be able to pick up equipment that gets dropped
## by a player? This defaults to false as if a player drops
## a piece of loot with a low drop rate and a mob picks it
## up, the mob might not drop the item when it dies. The laws
## of item dropping chance still apply.
  can-mobs-pick-up-equipment: false
  blank-mob-spawn:
## Should mobs have any pre-existing equipment removed when
## they spawn? This defaults to false as Minecraft now
## occasionally will spawn monsters with helmets, chestplates,
## leggings, boots, or weapons.
    enabled: false
## When removing pre-existing equipment, should bows be
## removed from skeletons?
    skeletons-spawn-without-bow: false
## Allow items to be repaired using an Anvil?
## This defaults to false as items can be renamed using the Anvil.
  allow-items-to-be-repaired-by-anvil: false
## Allow items to be equipped from the item bar using right clicks?
## This defaults to false as there have been associated item
## dupe bugs associated with this.
  allow-equipping-items-via-right-click: false
## Should leather colors be randomized?
  randomize-leather-colors: true
multiworld:
## Include any worlds where you want to have MythicDrops
## create drops here.
## Example:
##
## enabled-worlds:
## - world
## - world2
## - world3
  enabled-worlds:
  - WWW
  - Gavania
## All entries in this section have a maximum value of
## 1.0 (100%) and a minimum value of 0.0 (0%).
drops:
## This is the chance for a mob to get items at all.
## This is also coincidentally the chance for a mob
## to get an item with a tier.
  item-chance: 0.1
## If a mob does not receive an item with a tier,
## this is the chance for a mob to spawn with a
## custom item.
  custom-item-chance: 0.0
## If a mob does not receive an item with a tier
## or a custom item, this is the chance for a mob
## to spawn with a socket gem.
  socket-gem-chance: 0.0
## If a mob does not receive an item with a tier
## a custom item, or a socket gem, this is the chance for a mob
## to spawn with an unidentified item.
  unidentified-item-chance: 0.0
## If a mob does not receive an item with a tier
## a custom item, a socket gem, or an unidentified item,
## this is the chance for a mob to spawn with an identity tome.
  identity-tome-chance: 0.0
components:
## Should creatures be able to spawn with items?
  creature-spawning-enabled: true
## Should MythicDrops enable its repairing feature
## and disable the vanilla Minecraft repairing
## feature (recommended)?
  repairing-enabled: true
## Should MythicDrops spawn items with empty sockets
## and socket gems?
  socketting-enabled: false
## Should MythicDrops enable its identifying feature
## and spawn unidentified items and identity tomes?
  identifying-enabled: false
## Should MythicDrops enable distance-from-spawn
## based drops, i.e., drops that can only spawn within
## certain distances from the spawn of a world?
  distance-zones-enabled: false
display:
## How should the name of generated items be formatted?
## Uses variables contained in variables.txt.
  item-display-name-format: '%generalprefix% %itemtype%'
## How should the lore of generated items be formatted?
## Uses variables contained in variables.txt.
  tooltip-format:
  - '%baselore%'
  - '%bonuslore%'
  - '%socketlore%'
  - ''
  - '&7Tier:%tiercolor% %tiername%'