# 
# CONFIGURATION INFORMATION AVAILABLE AT: http://www.mythicmobs.net

Configuration:
  Version: 4.0
  General:
    AllowMetrics: true
    CheckForUpdates: true
    CompatibilityMode: false
    DebugLevel: 0
    ErrorLogging: true
    UseVolatileFeatures: true
  Clock:
    ClockInterval: 5
    SaveInterval: 5
    SpawnsInterval: 2
    ScannerInterval: 10
    CleanupInterval: 600
  Components:
    CustomSpawners: true
    RandomSpawning: true
  Mobs:
    DespawnByDefault: true
    EnableAIModifiers: true
    EnableTimerSkills: true
    EnableThreatTables: true
    EnablePlayerFactions: true
    EnableLegacySkills: true
    KillMessagePrefix: ''
    ShowHealth:
      Radius: 64
      Format: 
      #Format: &elvl &f<mob.level> <mob.name> - <mob.php> (<mob.hp> / <mob.mhp>)
    Scaling:
      Gavania:
        Enabled: true
        PerBlocksFromSpawn: 64
      Gavania_nether:
        Enabled: true
        PerBlocksFromSpawn: 64
      world2_nether:
        Enabled: false
        PerBlocksFromSpawn: 100
    DefaultLevelModifiers:
      Health: 2
      Armor: 0
      Damage: 2
      KnockbackResistance: 0
      MovementSpeed: 0
      Power: 0
      AttackSpeed: 0
  RandomSpawning:
    GenerateSpawnPoints: false
    MaxMobsPerChunk: 80
    SpawnRadiusPerPlayer: 128
    SpawnRadiusPerPlayerY: 48
    DespawnLazyRandomMobs: true
    MaxGenerationTime: 20
    PointsPerSecond:
      Land: 10
      Air: 0
      Sea: 0
      Lava: 0
      Ground: 0
  Compatibility:
    Heroes:
      Enabled: false
      ShowXPMessage: true
      XPMessageFormat: You receive <drops.xp> experience for slaying <mob.name>
    McMMO:
      Enabled: false
      ShowXPMessage: true
      XPMessageFormat: You receive <drops.xp> experience for slaying <mob.name>
    SkillAPI:
      Enabled: true
      ShowXPMessage: true
      XPMessageFormat: You receive <drops.xp> experience for slaying <mob.name>
    Vault:
      Enabled: true
      ShowMoneyMessage: true
      MoneyMessageFormat: You receive <drops.money> currency for slaying <mob.name>
